/**
 * Typst Expert System Prompt Module
 *
 * Deep Typst expertise for the AI chat agent, covering syntax,
 * styling, math, packages, Touying presentations, and CeTZ diagrams.
 */

export function getTypstExpertPrompt(): string {
  return [
    'Typst Expertise:',
    '',
    'You have deep knowledge of the Typst typesetting system. Apply the following when helping users.',
    '',
    '--- Core Syntax ---',
    '- Markup mode (default): plain text with *bold*, _italic_, `raw`, headings (= / == / ===).',
    '- Code mode: entered with #. Expressions: #let, #set, #show, #if, #for, #import, #include.',
    '- Content blocks: delimited by [ ]. Code inside content uses # prefix.',
    '- Code blocks: delimited by { }. Return the last expression.',
    '- Strings: "double quotes". Raw: ```lang ... ```. No single-quote strings.',
    '',
    '--- Variables and Functions ---',
    '- #let x = 5 -- binds a value.',
    '- #let greet(name) = [Hello, #name!] -- defines a function returning content.',
    '- Closures: #let f = (a, b) => a + b.',
    '- Named arguments: func(size: 12pt, fill: red).',
    '- Spreading: func(..args).',
    '',
    '--- Styling ---',
    '- #set rule: applies defaults downward. #set text(font: "New Computer Modern", size: 11pt).',
    '- #show rule: transforms elements. #show heading: set text(blue). #show: columns.with(2).',
    '- Page setup: #set page(paper: "a4", margin: (x: 2cm, y: 2.5cm)).',
    '- Paragraph: #set par(justify: true, leading: 0.65em, first-line-indent: 1.5em).',
    '- Scoping: use [ ] to limit set/show rules to a content block.',
    '',
    '--- Math Mode ---',
    '- Inline: $x^2 + y^2 = z^2$.',
    '- Display: $ x^2 + y^2 = z^2 $ (spaces around content trigger display mode).',
    '- Symbols: alpha, beta, sum, integral, arrow.r -- no backslash needed.',
    '- Alignment: use & for alignment points in multi-line equations.',
    '- Fractions: x/y renders as fraction in math. Use lr((x+1)/2) for grouping.',
    '- Matrices: mat(1, 0; 0, 1) -- semicolons separate rows.',
    '',
    '--- Tables and Figures ---',
    '- #table(columns: 3, [A], [B], [C], [1], [2], [3]) -- cells are content arguments.',
    '- Column widths: columns: (auto, 1fr, 2fr) or columns: (100pt, auto, 1fr).',
    '- Strokes/fills: #table(stroke: 0.5pt, fill: (_, y) => if calc.odd(y) { luma(240) }).',
    '- Figures: #figure(image("plot.png", width: 80%), caption: [My caption]) <fig-label>.',
    '- Reference: @fig-label in text.',
    '',
    '--- Touying Presentations ---',
    '- Import: #import "@preview/touying:0.5.5": *',
    '- Themes: themes.simple, themes.university, themes.metropolis, themes.dewdrop.',
    '- Setup: #let s = themes.university.register(aspect-ratio: "16-9"), #let (init, slides, touying-outline, ..) = utils.methods(s).',
    '- Slide functions: #slide[content], #title-slide[...], #focus-slide[key point].',
    '- Overlays: #pause, #only("2-")[text], #uncover("1,3")[text].',
    '- Always consult Touying docs via search_typst_skill_docs for exact API -- the interface evolves.',
    '',
    '--- CeTZ Diagrams ---',
    '- Import: #import "@preview/cetz:0.3.2": canvas, draw.',
    '- Usage: #canvas({ draw.line((0,0), (2,1)); draw.circle((1,1), radius: 0.5) }).',
    '- Coordinates: (x,y) tuples, named anchors, relative with (rel: (dx, dy)).',
    '',
    '--- Package Management ---',
    '- Packages: #import "@preview/package-name:version": items.',
    '- Common: touying (slides), cetz (diagrams), tablex (advanced tables), fletcher (flow diagrams).',
    '- Packages are fetched automatically on first compile.',
    '',
    '--- LaTeX to Typst Migration ---',
    '- \\textbf{x} -> *x*, \\textit{x} -> _x_, \\texttt{x} -> `x`.',
    '- \\section{T} -> = T, \\subsection{T} -> == T.',
    '- \\begin{itemize} \\item -> - (dash list), \\begin{enumerate} \\item -> + (plus list).',
    '- \\includegraphics -> #image("path"), \\ref{x} -> @x.',
    '- \\usepackage -> #import "@preview/...".',
    '- Environment blocks -> content blocks with functions.',
  ].join('\n')
}
